package com.aridclown.intellij.defold

import com.aridclown.intellij.defold.templates.AppManifestBuilder
import com.aridclown.intellij.defold.templates.AppManifestConfig
import com.aridclown.intellij.defold.templates.AppManifestExclusion
import com.aridclown.intellij.defold.templates.GameProjectAppManifest
import com.aridclown.intellij.defold.templates.GameProjectAppManifest.APP_MANIFEST_KEY
import com.aridclown.intellij.defold.templates.GameProjectAppManifest.GENERATED_APP_MANIFEST_VALUE
import com.aridclown.intellij.defold.templates.GameProjectAppManifest.NATIVE_EXTENSION_SECTION
import com.aridclown.intellij.defold.templates.GraphicsAdapter
import org.assertj.core.api.Assertions.assertThat
import org.ini4j.Config
import org.ini4j.Ini
import org.junit.jupiter.api.Test
import java.io.ByteArrayOutputStream
import java.io.StringReader

class GenerateManifestTest {
    @Test
    fun `manifest covers every supported defold platform`() {
        val manifest = AppManifestBuilder.build(AppManifestConfig())

        assertThat(manifest).startsWith("# Generated by IntelliJ-Defold\nplatforms:\n")
        AppManifestBuilder.ALL_PLATFORMS.forEach { platform ->
            assertThat(manifest).contains("    $platform:\n        context:")
        }
    }

    @Test
    fun `empty config produces empty per-platform context blocks`() {
        val manifest = AppManifestBuilder.build(AppManifestConfig())

        AppManifestBuilder.ALL_PLATFORMS.forEach { platform ->
            assertThat(platformContext(manifest, platform))
                .containsExactly(
                    "excludeLibs: []",
                    "excludeSymbols: []",
                    "libs: []",
                    "frameworks: []"
                )
        }
    }

    @Test
    fun `exclude physics 2d emits box2d in excludeLibs for every native platform`() {
        val manifest = AppManifestBuilder.build(
            AppManifestConfig(exclusions = setOf(AppManifestExclusion.PHYSICS_2D))
        )

        AppManifestBuilder.ALL_PLATFORMS.forEach { platform ->
            assertThat(platformContext(manifest, platform))
                .extracting<String> { it }
                .first()
                .isEqualTo("""excludeLibs: ["box2d_defold"]""")
        }
    }

    @Test
    fun `exclude sound emits libs symbols and excludes for every native platform`() {
        val manifest = AppManifestBuilder.build(
            AppManifestConfig(exclusions = setOf(AppManifestExclusion.SOUND))
        )

        AppManifestBuilder.ALL_PLATFORMS.forEach { platform ->
            assertThat(platformContext(manifest, platform))
                .containsExactly(
                    """excludeLibs: ["sound", "tremolo"]""",
                    """excludeSymbols: ["DefaultSoundDevice", "AudioDecoderWav", "AudioDecoderStbVorbis", "AudioDecoderTremolo"]""",
                    """libs: ["sound_null"]""",
                    "frameworks: []"
                )
        }
    }

    @Test
    fun `combining basis transcoder with vulkan only merges directives per platform`() {
        val manifest = AppManifestBuilder.build(
            AppManifestConfig(
                exclusions = setOf(AppManifestExclusion.BASIS_TRANSCODER),
                graphics = GraphicsAdapter.VULKAN_ONLY
            )
        )

        // Native platforms get both basis-transcoder and graphics-vulkan-only directives merged.
        assertThat(platformContext(manifest, "x86_64-osx"))
            .containsExactly(
                """excludeLibs: ["graphics_transcoder_basisu", "graphics"]""",
                """excludeSymbols: ["GraphicsAdapterBasisTranscoder", "GraphicsAdapterOpenGL"]""",
                """libs: ["graphics_transcoder_null", "graphics_vulkan"]""",
                "frameworks: []"
            )

        // Web platforms keep only the transcoder directives — no Vulkan there.
        assertThat(platformContext(manifest, "js-web"))
            .containsExactly(
                """excludeLibs: ["graphics_transcoder_basisu"]""",
                """excludeSymbols: ["GraphicsAdapterBasisTranscoder"]""",
                """libs: ["graphics_transcoder_null"]""",
                "frameworks: []"
            )
    }

    @Test
    fun `opengl only excludes the vulkan adapter only on native platforms`() {
        val manifest = AppManifestBuilder.build(
            AppManifestConfig(graphics = GraphicsAdapter.OPENGL_ONLY)
        )

        assertThat(platformContext(manifest, "x86_64-osx"))
            .containsExactly(
                """excludeLibs: ["graphics_vulkan"]""",
                """excludeSymbols: ["GraphicsAdapterVulkan"]""",
                "libs: []",
                "frameworks: []"
            )
        assertThat(platformContext(manifest, "wasm-web"))
            .containsExactly(
                "excludeLibs: []",
                "excludeSymbols: []",
                "libs: []",
                "frameworks: []"
            )
    }

    @Test
    fun `applying to game project ini sets native_extension app_manifest key`() {
        val ini = parseIni(
            """
            [project]
            title = MyGame

            [bootstrap]
            main_collection = /main/main.collectionc
            """.trimIndent()
        )

        GameProjectAppManifest.apply(ini)

        assertThat(ini[NATIVE_EXTENSION_SECTION]).isNotNull
        assertThat(ini[NATIVE_EXTENSION_SECTION]!![APP_MANIFEST_KEY])
            .isEqualTo(GENERATED_APP_MANIFEST_VALUE)
            .isEqualTo("/generated.appmanifest")
    }

    @Test
    fun `applying to game project ini preserves other sections and is idempotent`() {
        val ini = parseIni(
            """
            [project]
            title = MyGame

            [bootstrap]
            main_collection = /main/main.collectionc
            """.trimIndent()
        )

        GameProjectAppManifest.apply(ini)
        val afterFirst = serialize(ini)

        GameProjectAppManifest.apply(ini)
        val afterSecond = serialize(ini)

        assertThat(ini["project"]!!["title"]).isEqualTo("MyGame")
        assertThat(ini["bootstrap"]!!["main_collection"]).isEqualTo("/main/main.collectionc")
        assertThat(ini[NATIVE_EXTENSION_SECTION]!![APP_MANIFEST_KEY])
            .isEqualTo("/generated.appmanifest")
        assertThat(afterSecond).isEqualTo(afterFirst)
    }

    @Test
    fun `applying overwrites an existing app_manifest value`() {
        val ini = parseIni(
            """
            [native_extension]
            app_manifest = /custom.appmanifest
            """.trimIndent()
        )

        GameProjectAppManifest.apply(ini)

        assertThat(ini[NATIVE_EXTENSION_SECTION]!![APP_MANIFEST_KEY])
            .isEqualTo("/generated.appmanifest")
    }

    private fun platformContext(manifest: String, platform: String): List<String> {
        val header = "    $platform:\n        context:\n"
        val start = manifest.indexOf(header)
        require(start >= 0) { "platform $platform not found in manifest:\n$manifest" }
        val contextStart = start + header.length
        return manifest.substring(contextStart)
            .lineSequence()
            .takeWhile { it.startsWith("            ") }
            .map { it.trim() }
            .toList()
    }

    private fun parseIni(text: String): Ini = Ini().apply {
        config = Config().apply { isEscape = false }
        StringReader(text).use(::load)
    }

    private fun serialize(ini: Ini): String = ByteArrayOutputStream().use {
        ini.store(it)
        it.toString(Charsets.UTF_8)
    }
}
