package com.aridclown.intellij.defold.templates

import com.aridclown.intellij.defold.templates.AppManifestExclusion.BASIS_TRANSCODER
import com.aridclown.intellij.defold.templates.AppManifestExclusion.INPUT
import com.aridclown.intellij.defold.templates.AppManifestExclusion.LIVEUPDATE
import com.aridclown.intellij.defold.templates.AppManifestExclusion.PHYSICS_2D
import com.aridclown.intellij.defold.templates.AppManifestExclusion.PHYSICS_3D
import com.aridclown.intellij.defold.templates.AppManifestExclusion.PROFILER
import com.aridclown.intellij.defold.templates.AppManifestExclusion.RECORD
import com.aridclown.intellij.defold.templates.AppManifestExclusion.SOUND
import com.aridclown.intellij.defold.templates.GraphicsAdapter.BOTH
import com.aridclown.intellij.defold.templates.GraphicsAdapter.OPENGL_ONLY
import com.aridclown.intellij.defold.templates.GraphicsAdapter.VULKAN_ONLY

/**
 * Stateless builder that emits a Defold-flavored app-manifest YAML from an
 * [AppManifestConfig]. Mirrors britzl/manifestation and the Defold editor's
 * own generator: per-platform `excludeLibs` / `excludeSymbols` / `libs` /
 * `frameworks` blocks under a top-level `platforms:` map.
 *
 * The output is intentionally deterministic so it can be diffed and tested
 * byte-for-byte.
 */
object AppManifestBuilder {
    /**
     * Platforms covered by the generated manifest. Order is significant —
     * it is preserved verbatim in the YAML output.
     */
    val ALL_PLATFORMS: List<String> = listOf(
        "x86_64-osx",
        "arm64-osx",
        "x86_64-win32",
        "x86_64-linux",
        "armv7-android",
        "arm64-android",
        "arm64-ios",
        "x86_64-ios",
        "js-web",
        "wasm-web"
    )

    fun build(config: AppManifestConfig): String {
        val byPlatform = LinkedHashMap<String, PlatformContext>()
        for (platform in ALL_PLATFORMS) {
            byPlatform[platform] = contextFor(config, platform)
        }
        return emitYaml(byPlatform)
    }

    private fun contextFor(config: AppManifestConfig, platform: String): PlatformContext {
        var ctx = PlatformContext()
        for (exclusion in config.exclusions) {
            ctx = ctx.merge(directivesFor(exclusion))
        }
        ctx = ctx.merge(graphicsDirectivesFor(config.graphics, platform))
        return ctx
    }

    private fun directivesFor(exclusion: AppManifestExclusion): PlatformContext = when (exclusion) {
        PHYSICS_2D -> PlatformContext(excludeLibs = listOf("box2d_defold"))

        PHYSICS_3D -> PlatformContext(
            excludeLibs = listOf("BulletDynamics", "BulletCollision", "LinearMath")
        )

        RECORD -> PlatformContext(
            excludeLibs = listOf("record"),
            libs = listOf("record_null")
        )

        PROFILER -> PlatformContext(
            excludeLibs = listOf("profilerext"),
            libs = listOf("profilerext_null"),
            excludeSymbols = listOf("ProfilerExt")
        )

        SOUND -> PlatformContext(
            excludeLibs = listOf("sound", "tremolo"),
            libs = listOf("sound_null"),
            excludeSymbols = listOf(
                "DefaultSoundDevice",
                "AudioDecoderWav",
                "AudioDecoderStbVorbis",
                "AudioDecoderTremolo"
            )
        )

        INPUT -> PlatformContext(
            excludeLibs = listOf("hid"),
            libs = listOf("hid_null")
        )

        LIVEUPDATE -> PlatformContext(
            excludeLibs = listOf("liveupdate"),
            libs = listOf("liveupdate_null"),
            excludeSymbols = listOf("LiveUpdateExt")
        )

        BASIS_TRANSCODER -> PlatformContext(
            excludeLibs = listOf("graphics_transcoder_basisu"),
            libs = listOf("graphics_transcoder_null"),
            excludeSymbols = listOf("GraphicsAdapterBasisTranscoder")
        )
    }

    private fun graphicsDirectivesFor(graphics: GraphicsAdapter, platform: String): PlatformContext {
        // Web targets do not have a Vulkan adapter; leave their graphics block untouched.
        if (platform.endsWith("-web")) return PlatformContext()
        return when (graphics) {
            BOTH -> PlatformContext()

            OPENGL_ONLY -> PlatformContext(
                excludeLibs = listOf("graphics_vulkan"),
                excludeSymbols = listOf("GraphicsAdapterVulkan")
            )

            VULKAN_ONLY -> PlatformContext(
                excludeLibs = listOf("graphics"),
                libs = listOf("graphics_vulkan"),
                excludeSymbols = listOf("GraphicsAdapterOpenGL")
            )
        }
    }

    private fun emitYaml(byPlatform: Map<String, PlatformContext>): String = buildString {
        appendLine("# Generated by IntelliJ-Defold")
        appendLine("platforms:")
        for ((platform, ctx) in byPlatform) {
            appendLine("    $platform:")
            appendLine("        context:")
            appendLine("            excludeLibs: ${yamlList(ctx.excludeLibs)}")
            appendLine("            excludeSymbols: ${yamlList(ctx.excludeSymbols)}")
            appendLine("            libs: ${yamlList(ctx.libs)}")
            appendLine("            frameworks: ${yamlList(ctx.frameworks)}")
        }
    }

    private fun yamlList(items: List<String>): String = if (items.isEmpty()) {
        "[]"
    } else {
        items.joinToString(prefix = "[", postfix = "]") { "\"$it\"" }
    }
}
